name: 'Deploy to Netlify'
on:
  push:
    branches:
      - [main] 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: 'Install Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: 'Install dependencies'
        run: yarn
      - name: 'Build the site'
        run: vite build
      - name: 'Deploy to Netlify'
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
