name: 'Netlify Deploy'
on:
  push:
    branches: [main]
jobs:
  # deploy the application to netlify
  deploy:
    name: 'Deploy Production build to netlify'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to netlify
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.MY_NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: 'dist'
          install_command: 'yarn'
          build_command: 'yarn build'
          deploy_alias: 'melsonic'
